# Site settings
baseurl = "https://about.txtdirect.org/"
languageCode = "en-us"
title = "txtdirect - DNS TXT-record based redirects"
theme = "syna"
version = "0.1.0"

DefaultContentLanguage = "en"

[params]
  name = "Okkur Labs"
  description = "DNS TXT-record based redirects"
  image = "header.jpg"

  # Branding options
  [params.branding]
    logoNavigation = "logo.svg"
    textNavigation = "TXTdirect"

  [params.style]
    backgroundNavigation = "light"
    backgroundFooter = "primary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "favicon.ico"
    faviconICOSizes = "16x16 32x32"
    faviconPNG = "favicon.png"
    faviconSVG = "favicon.svg"
    iconFont = ""
    css = ["overwrite.css"]
    js  = []

  # Repository Button
  [params.repoButton]
    url = "https://github.com/txtdirect/txtdirect"
    text = "Star" # default: "Star"
    icon = "fa-github" # default: "fa-github"

  # Piwik tracking
  [params.analytics.piwik]
    url = "https://stats.seetheprogress.com"
    id = "12"
    domain = "about.txtdirect.org" # Track subdomains via "*.example.com"

  [params.contact]
    disabled = false

[[menu.legalFooter]]
  url = "https://about.seetheprogress.com/about/"
  name = "About Us"
  weight = 10
